/**
 * @description 权限列表(数据从后端取), 仅供开发时提供 ts 类型提示，无实际作用
 */
const permissions = [
  'system:user:list',
  'system:role:list',
  'system:menu:list',
  'system:online:list',
  'system:log:login:list',
  'system:serve:stat',
  'system:task:list',
  'dashboard:workbench',
  'dashboard:analysis',
  'system:user:read',
  'system:user:create',
  'system:user:delete',
  'system:user:update',
  'system:role:create',
  'system:role:delete',
  'system:role:update',
  'system:role:read',
  'system:menu:create',
  'system:menu:delete',
  'system:menu:update',
  'system:menu:read',
  'system:online:kick',
  'system:task:create',
  'system:task:delete',
  'system:task:once',
  'system:task:read',
  'system:task:start',
  'system:task:stop',
  'system:task:update',
  'system:log:task:list',
  'system:tool:email',
  'tool:email:send',
  'tool:storage:list',
  'upload:upload',
  'tool:storage:delete',
  'system:user:password',
  'system:dict-type:list',
  'system:dict-type:create',
  'system:dict-type:update',
  'system:dict-type:delete',
  'system:dict-type:info',
  'system:dict-item:list',
  'system:dict-item:create',
  'system:dict-item:update',
  'system:dict-item:delete',
  'system:dict-item:info',
  'system:param-config:list',
  'system:param-config:create',
  'system:param-config:update',
  'system:param-config:delete',
  'system:param-config:info',
  'system:dept:list',
  'system:dept:create',
  'system:dept:update',
  'system:dept:delete',
  'system:dept:read',
  'app:health:network',
  'app:health: database',
  'todo:create',
  'todo:update',
  'todo:delete',
  'todo:read',
  'todo:list',
] as const;

export type PermissionType = (typeof permissions)[number];

// console.log('permissions', permissions);
