// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ACard: typeof import('ant-design-vue/es')['Card'];
    AInput: typeof import('ant-design-vue/es')['Input'];
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
    BasicBasicHelp: typeof import('./src/components/basic/basic-help/index.vue')['default'];
    BasicButtonButton: typeof import('./src/components/basic/button/button.vue')['default'];
    BasicCheckBox: typeof import('./src/components/basic/check-box/index.vue')['default'];
    BasicContextMenuSrcContextMenu: typeof import('./src/components/basic/context-menu/src/ContextMenu.vue')['default'];
    BasicExcelSrcImportExcel: typeof import('./src/components/basic/excel/src/ImportExcel.vue')['default'];
    BasicIconsSelect: typeof import('./src/components/basic/icons-select/index.vue')['default'];
    BasicLocalePicker: typeof import('./src/components/basic/locale-picker/index.vue')['default'];
    BasicLockscreen: typeof import('./src/components/basic/lockscreen/index.vue')['default'];
    BasicLockscreenHuaweiCharge: typeof import('./src/components/basic/lockscreen/huawei-charge.vue')['default'];
    BasicLockscreenLockscreen: typeof import('./src/components/basic/lockscreen/lockscreen.vue')['default'];
    BasicLockscreenXiaomiCharge: typeof import('./src/components/basic/lockscreen/xiaomi-charge.vue')['default'];
    BasicProgress: typeof import('./src/components/basic/progress/index.vue')['default'];
    BasicSplitPanel: typeof import('./src/components/basic/split-panel/index.vue')['default'];
    BasicSvgIconSvgIcon: typeof import('./src/components/basic/svg-icon/svg-icon.vue')['default'];
    BasicTitleI18n: typeof import('./src/components/basic/title-i18n/index.vue')['default'];
    CoreDraggableModal: typeof import('./src/components/core/draggable-modal/index.vue')['default'];
    CoreDynamicTableComponentsQueryForm: typeof import('./src/components/core/dynamic-table/components/query-form/index.vue')['default'];
    CoreDynamicTableComponentsTableAction: typeof import('./src/components/core/dynamic-table/components/table-action.vue')['default'];
    CoreDynamicTableComponentsTableSettings: typeof import('./src/components/core/dynamic-table/components/table-settings/index.vue')['default'];
    CoreDynamicTableComponentsTableSettingsColumnSetting: typeof import('./src/components/core/dynamic-table/components/table-settings/column-setting.vue')['default'];
    CoreDynamicTableComponentsTableSettingsRefreshSetting: typeof import('./src/components/core/dynamic-table/components/table-settings/refresh-setting.vue')['default'];
    CoreDynamicTableComponentsTableSettingsSizeSetting: typeof import('./src/components/core/dynamic-table/components/table-settings/size-setting.vue')['default'];
    CoreDynamicTableComponentsToolBar: typeof import('./src/components/core/dynamic-table/components/tool-bar/index.vue')['default'];
    CoreDynamicTableDynamicTable: typeof import('./src/components/core/dynamic-table/dynamic-table.vue')['default'];
    CoreSchemaFormSchemaForm: typeof import('./src/components/core/schema-form/schema-form.vue')['default'];
    CoreSchemaFormSchemaFormItem: typeof import('./src/components/core/schema-form/schema-form-item.vue')['default'];
  }
}

export {};
